### ISSUE TITLE
simple module on 20.09

### ISSUE THREAD

**Issue by timhae** [helsinki-systems/bbb4nix#93]
Hey, many thanks for your efforts. I tried setting up the module on my 20.09 NixOS VPS. Here is what I did in my `configuration.nix`:
```
imports = [
  /path/to/repo/bbb4nix/modules
  /path/to/repo/bbb4nix/modules/helsinki
];
services.bigbluebutton.simple = {
  enable = true;
  domain = "bbb.my.domain";
  ips = [ "my.public.ip.here" ];
};
```
When I rebuild I get `error: The option 'helsinki.firewall' defined in '/path/to/repo/bbb4nix/modules/coturn.nix' does not exist.`. Changing `modules/coturn.nix` with this patch
```
diff --git a/modules/coturn.nix b/modules/coturn.nix
index 005787a..c196240 100644
--- a/modules/coturn.nix
+++ b/modules/coturn.nix
@@ -44,13 +44,30 @@ in {
       '';
     };

-    helsinki.firewall.ports = {
-      multi = [
-        "3478-3479" # Listening ports
-        "5349-5350" # TLS listening ports
+    networking.firewall = {
+      allowedTCPPortRanges = [
+        {
+          from = 3478;
+          to = 3479;
+        }
+        {
+          from = 5349;
+          to = 5350;
+        }
       ];
-      udp = [
-        "49152-65535"
+      allowedUDPPortRanges  = [
+        {
+          from = 3478;
+          to = 3479;
+        }
+        {
+          from = 5349;
+          to = 5350;
+        }
+        {
+          from = 49152;
+          to = 65535;
+        }
       ];
     };
```
fails with `error: The option 'services.coturn.enable' in '/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/services/networking/coturn.nix' is already declared in '/path/to/repo/bbb4nix/modules/helsinki/coturn.nix'.`. Do you have any clue what I could do to make this module work?

**Comment by ajs124** [comment]
For reasons which I don't remember, we apparently have a "fork" of the coturn module. So you either need to disable that in modules/helsinki/default.nix and see if the regular coturn module from nixpkgs works or you can use disabledModules in your configuration to disable the module from nixpkgs.

**Comment by timhae** [comment]
Thanks for getting back to me. After disabling nixpkgs coturn and this patch
```
diff --git a/modules/helsinki/cooler-postgresql.nix b/modules/helsinki/cooler-postgresql.nix
index db8c5f8..0637c5c 100644
--- a/modules/helsinki/cooler-postgresql.nix
+++ b/modules/helsinki/cooler-postgresql.nix
@@ -276,7 +276,7 @@ in {
       };

       apparmor = {
-        enable2 = true;
+        enable = true;
         packages = [ cfg.package ];
         extraConfig = ''
           /etc/passwd r,
diff --git a/modules/helsinki/cooler-redis.nix b/modules/helsinki/cooler-redis.nix
index 928ef4a..f319ff8 100644
--- a/modules/helsinki/cooler-redis.nix
+++ b/modules/helsinki/cooler-redis.nix
@@ -71,7 +71,7 @@ in {
       };

       apparmor = {
-        enable2 = true;
+        enable = true;
         extraConfig = ''
@{PROC}@{pid}/stat r,
```
I get `error: attribute 'bbbPackages' missing, at /path/to/repo/bbb4nix/modules/nginx.nix:139:16`. Any ideas?

**Comment by ajs124** [comment]
Right. Looks like we only ever imported the packages into an overlay internally. You can just add something like this to your config:
```
nixpkgs.overlays = [ (self: super: {
  inherit (super.callPackage bbb4nix/packages {}) bbbPackages kurentoPackages freeswitchPackages;
}) ];
```

**Comment by timhae** [comment]
That leaves me with `error: The option 'services.bigbluebutton.greenlight.adminName' is used but not defined.` just hardcoding all those options (also the password) leads to `error: anonymous function at /path/to/repo/bbb4nix/packages/bbb-greenlight/default.nix:1:1 called without required argument 'dockerignored', at /nix/store/wmc9mmax4c7d5b7p78iw5n40jd70c2a2-nixos-20.09.3346.4d0ee90c6e2/nixos/lib/customisation.nix:69:16`
but it feels like I am close.. :D bbb seems to be quite a package to build..

**Comment by timhae** [comment]
I just found [dockerignored](https://github.com/helsinki-systems/dockerignored) :P but that fails to build with `error: anonymous function at /path/to/repo/dockerignored/default.nix:1:1 called with unexpected argument 'config', at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:269:8`. Just adding the `config` parameter in the function argument list leaves me with `error: syntax error, unexpected ID, expecting '.' or '=', at /path/to/repo/dockerignored/default.nix:1:10` unfortunately my nix knowledge is not that good so I am lost :( any ideas?

**Comment by timhae** [comment]
I forgot a `,`.. changing the first line of dockerignored to `{ modulesPath, options, lib, config, buildGoPackage, fetchFromGitHub, writeText }:` fails with infinite recursion though. I added the other parameters because nix complained about unexpected arguments so maybe the place where this is called needs to be adapted?

**Comment by ajs124** [comment]
As far as I remember, `dockerignored` is just a nice-to-have, so if you drop it from the greenlight package, it should still work.

**Comment by timhae** [comment]
I removed `dockerignored` and now face `error: anonymous function at /path/to/repo/bbb4nix/packages/bbb-webrtc-sfu/default.nix:1:1 called without required argument 'util-linux', at /nix/store/6mqk2z3w8bc9vw2l4j9yzfqbg24d7glx-nixos-20.09.3368.16fc9eb7364/nixos/lib/customisation.nix:69:16`. Thanks for your persistence by the way.

**Comment by timhae** [comment]
`util-linux` is called `utillinux` in nixos 20.09 which I am using on my server.. It is building now, I can post the entire change set if you are interested

**Comment by ajs124** [comment]
Ah, yeah. That was changed in b63de6f3cc0f9c5b4f5ab23b6e4c6cca53c4598a, to be compatible with 21.05 and we aliased it in our overlay.

**Comment by timhae** [comment]
Alright, I think I hit a wall here.. [this](https://pastebin.com/Xxxyxwkn) is my changeset so far, I run the `generate.sh` script and building results in [this](https://pastebin.com/MQCxTKz2) error. Here is my `configuration.nix`:
```
services.bigbluebutton.simple = {
  enable = true;
  domain = "bbb.my.domain";
  ips = [ "1.2.3.4" "1212:1234::1" ];
};
```
Do you have any clues? And thanks again for the help!

**Comment by ajs124** [comment]
You shouldn't need run any of the scripts (well, except for the bbb-html5 one, because #33), you should just be able to deploy it with the nix files.

If you want newer versions of the components, just pick the patches from the unstable branch.

Edit: That greenlight build failure doesn't look familiar. The ruby stuff was always some of the least painful, so idk what could be happening here.

**Comment by timhae** [comment]
Please excuse the long wait.. So I reset  everything and only ran the `generate.sh` script for bbb-html5, now it builds nicely but redis seems to have an issue:
```
● redis-bigbluebutton.service - Redis instance bigbluebutton
     Loaded: loaded (/nix/store/xyiiaavbqkpjwaf3kc7k5vc1531zaki6-unit-redis-bigbluebutton.service/redis-bigbluebutton.service; enabled; vendor preset: enabled)
     Active: failed (Result: protocol) since Sun 2021-03-14 15:55:02 CET; 11min ago
    Process: 2072 ExecStart=/nix/store/7xr4k4nn6hix8537pz9hfxvb43mkwbcz-redis-6.0.11/bin/redis-server /nix/store/5qp5h6b3v8v7qnkc3vqpwn62fanhab22-redis-bigbluebutton.conf     (code=exited, status=0/SUCCESS)
   Main PID: 2072 (code=exited, status=0/SUCCESS)
     Status: "Redis is loading..."
         IP: 0B in, 0B out
        CPU: 96ms

Mar 14 15:55:02 nixosServerNetcup1 systemd[1]: redis-bigbluebutton.service: Scheduled restart job, restart counter is at 5.
Mar 14 15:55:02 nixosServerNetcup1 systemd[1]: Stopped Redis instance bigbluebutton.
Mar 14 15:55:02 nixosServerNetcup1 systemd[1]: redis-bigbluebutton.service: Start request repeated too quickly.
Mar 14 15:55:02 nixosServerNetcup1 systemd[1]: redis-bigbluebutton.service: Failed with result 'protocol'.
Mar 14 15:55:02 nixosServerNetcup1 systemd[1]: Failed to start Redis instance bigbluebutton.
```
I don't know whats wrong here.. journalctl doesn't have anything usefull as well (at least to my eyes), manually starting redis gives:
```
❯ /nix/store/7xr4k4nn6hix8537pz9hfxvb43mkwbcz-redis-6.0.11/bin/redis-server /nix/store/5qp5h6b3v8v7qnkc3vqpwn62fanhab22-redis-bigbluebutton.conf
3666:C 14 Mar 2021 16:02:48.247 # WARNING supervised by systemd - you MUST set appropriate values for TimeoutStartSec and TimeoutStopSec in your service unit.
3666:C 14 Mar 2021 16:02:48.247 # systemd supervision requested, but NOTIFY_SOCKET not found
```
I assume the warnings are fine but [googling](https://serverfault.com/questions/1031891/redis-service-hangs-with-systemctl-and-type-notify) shows that systemd support might require rebuilding redis.. any ideas?

**Comment by timhae** [comment]
The systemctl log when restarting shows this:
```
Mar 15 08:45:30 nixosServerNetcup1 systemd[1]: Starting Redis instance bigbluebutton...
Mar 15 08:45:30 nixosServerNetcup1 redis-server[16592]: 16592:C 15 Mar 2021 08:45:30.990 # WARNING supervised by systemd - you MUST set appropriate values for TimeoutStartSec and TimeoutStopSec in your service unit.
Mar 15 08:45:30 nixosServerNetcup1 redis-server[16592]: WARNING supervised by systemd - you MUST set appropriate values for TimeoutStartSec and TimeoutStopSec in your service unit.
Mar 15 08:45:30 nixosServerNetcup1 systemd[1]: redis-bigbluebutton.service: Failed with result 'protocol'.
Mar 15 08:45:30 nixosServerNetcup1 systemd[1]: Failed to start Redis instance bigbluebutton.
Mar 15 08:45:31 nixosServerNetcup1 systemd[1]: redis-bigbluebutton.service: Scheduled restart job, restart counter is at 1.
Mar 15 08:45:31 nixosServerNetcup1 systemd[1]: Stopped Redis instance bigbluebutton.
Mar 15 08:45:31 nixosServerNetcup1 systemd[1]: Starting Redis instance bigbluebutton...
Mar 15 08:45:31 nixosServerNetcup1 redis-server[16598]: 16598:C 15 Mar 2021 08:45:31.345 # WARNING supervised by systemd - you MUST set appropriate values for TimeoutStartSec and TimeoutStopSec in your service unit.
Mar 15 08:45:31 nixosServerNetcup1 redis-server[16598]: WARNING supervised by systemd - you MUST set appropriate values for TimeoutStartSec and TimeoutStopSec in your service unit.
Mar 15 08:45:31 nixosServerNetcup1 systemd[1]: redis-bigbluebutton.service: Failed with result 'protocol'.
Mar 15 08:45:31 nixosServerNetcup1 systemd[1]: Failed to start Redis instance bigbluebutton.
Mar 15 08:45:31 nixosServerNetcup1 systemd[1]: redis-bigbluebutton.service: Scheduled restart job, restart counter is at 2.
Mar 15 08:45:31 nixosServerNetcup1 systemd[1]: Stopped Redis instance bigbluebutton.
Mar 15 08:45:31 nixosServerNetcup1 systemd[1]: Starting Redis instance bigbluebutton...
Mar 15 08:45:31 nixosServerNetcup1 redis-server[16603]: 16603:C 15 Mar 2021 08:45:31.595 # WARNING supervised by systemd - you MUST set appropriate values for TimeoutStartSec and TimeoutStopSec in your service unit.
Mar 15 08:45:31 nixosServerNetcup1 redis-server[16603]: WARNING supervised by systemd - you MUST set appropriate values for TimeoutStartSec and TimeoutStopSec in your service unit.
Mar 15 08:45:31 nixosServerNetcup1 redis-server[16605]: oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
Mar 15 08:45:31 nixosServerNetcup1 redis-server[16605]: Redis version=6.0.11, bits=64, commit=00000000, modified=0, pid=16605, just started
Mar 15 08:45:31 nixosServerNetcup1 redis-server[16605]: Configuration loaded
Mar 15 08:45:31 nixosServerNetcup1 redis[16605]: Running mode=standalone, port=6379.
Mar 15 08:45:31 nixosServerNetcup1 redis[16605]: Server initialized
Mar 15 08:45:31 nixosServerNetcup1 redis[16605]: Loading RDB produced by version 6.0.11
Mar 15 08:45:31 nixosServerNetcup1 redis[16605]: RDB age 59667 seconds
Mar 15 08:45:31 nixosServerNetcup1 redis[16605]: RDB memory usage when created 0.81 Mb
Mar 15 08:45:31 nixosServerNetcup1 redis[16605]: DB loaded from disk: 0.000 seconds
Mar 15 08:45:31 nixosServerNetcup1 systemd[1]: redis-bigbluebutton.service: Got notification message from PID 16605, but reception only permitted for main PID which is currently not known
Mar 15 08:45:31 nixosServerNetcup1 redis[16605]: Ready to accept connections
Mar 15 08:45:31 nixosServerNetcup1 systemd[1]: redis-bigbluebutton.service: Got notification message from PID 16605, but reception only permitted for main PID which is currently not known
Mar 15 08:45:31 nixosServerNetcup1 redis[16605]: The server is now ready to accept connections at /run/redis/bigbluebutton.sock
Mar 15 08:45:31 nixosServerNetcup1 systemd[1]: redis-bigbluebutton.service: Got notification message from PID 16605, but reception only permitted for main PID which is currently not known
Mar 15 08:45:31 nixosServerNetcup1 redis[16605]: User requested shutdown...
Mar 15 08:45:31 nixosServerNetcup1 systemd[1]: redis-bigbluebutton.service: Got notification message from PID 16605, but reception only permitted for main PID which is currently not known
Mar 15 08:45:31 nixosServerNetcup1 redis[16605]: Saving the final RDB snapshot before exiting.
Mar 15 08:45:31 nixosServerNetcup1 redis[16605]: DB saved on disk
Mar 15 08:45:31 nixosServerNetcup1 redis[16605]: Removing the pid file.
Mar 15 08:45:31 nixosServerNetcup1 redis[16605]: Removing the unix socket file.
Mar 15 08:45:31 nixosServerNetcup1 redis[16605]: Redis is now ready to exit, bye bye...
Mar 15 08:45:31 nixosServerNetcup1 systemd[1]: redis-bigbluebutton.service: Failed with result 'protocol'.
Mar 15 08:45:31 nixosServerNetcup1 systemd[1]: Failed to start Redis instance bigbluebutton.
Mar 15 08:45:31 nixosServerNetcup1 systemd[1]: redis-bigbluebutton.service: Scheduled restart job, restart counter is at 3.
Mar 15 08:45:31 nixosServerNetcup1 systemd[1]: Stopped Redis instance bigbluebutton.
Mar 15 08:45:31 nixosServerNetcup1 systemd[1]: Starting Redis instance bigbluebutton...
Mar 15 08:45:31 nixosServerNetcup1 redis-server[16613]: 16613:C 15 Mar 2021 08:45:31.846 # WARNING supervised by systemd - you MUST set appropriate values for TimeoutStartSec and TimeoutStopSec in your service unit.
Mar 15 08:45:31 nixosServerNetcup1 redis-server[16613]: WARNING supervised by systemd - you MUST set appropriate values for TimeoutStartSec and TimeoutStopSec in your service unit.
Mar 15 08:45:31 nixosServerNetcup1 redis-server[16615]: oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
Mar 15 08:45:31 nixosServerNetcup1 redis-server[16615]: Redis version=6.0.11, bits=64, commit=00000000, modified=0, pid=16615, just started
Mar 15 08:45:31 nixosServerNetcup1 redis-server[16615]: Configuration loaded
Mar 15 08:45:31 nixosServerNetcup1 redis[16615]: Running mode=standalone, port=6379.
Mar 15 08:45:31 nixosServerNetcup1 redis[16615]: Server initialized
Mar 15 08:45:31 nixosServerNetcup1 redis[16615]: Loading RDB produced by version 6.0.11
Mar 15 08:45:31 nixosServerNetcup1 redis[16615]: RDB age 0 seconds
Mar 15 08:45:31 nixosServerNetcup1 redis[16615]: RDB memory usage when created 0.77 Mb
Mar 15 08:45:31 nixosServerNetcup1 redis[16615]: DB loaded from disk: 0.000 seconds
Mar 15 08:45:31 nixosServerNetcup1 systemd[1]: redis-bigbluebutton.service: Got notification message from PID 16615, but reception only permitted for main PID which is currently not known
Mar 15 08:45:31 nixosServerNetcup1 redis[16615]: Ready to accept connections
Mar 15 08:45:31 nixosServerNetcup1 systemd[1]: redis-bigbluebutton.service: Got notification message from PID 16615, but reception only permitted for main PID which is currently not known
Mar 15 08:45:31 nixosServerNetcup1 redis[16615]: The server is now ready to accept connections at /run/redis/bigbluebutton.sock
Mar 15 08:45:31 nixosServerNetcup1 redis[16615]: User requested shutdown...
Mar 15 08:45:31 nixosServerNetcup1 redis[16615]: Saving the final RDB snapshot before exiting.
Mar 15 08:45:31 nixosServerNetcup1 systemd[1]: redis-bigbluebutton.service: Got notification message from PID 16615, but reception only permitted for main PID which is currently not known
Mar 15 08:45:31 nixosServerNetcup1 systemd[1]: redis-bigbluebutton.service: Got notification message from PID 16615, but reception only permitted for main PID which is currently not known
Mar 15 08:45:31 nixosServerNetcup1 redis[16615]: DB saved on disk
Mar 15 08:45:31 nixosServerNetcup1 redis[16615]: Removing the pid file.
Mar 15 08:45:31 nixosServerNetcup1 redis[16615]: Removing the unix socket file.
Mar 15 08:45:31 nixosServerNetcup1 redis[16615]: Redis is now ready to exit, bye bye...
Mar 15 08:45:31 nixosServerNetcup1 systemd[1]: redis-bigbluebutton.service: Failed with result 'protocol'.
Mar 15 08:45:31 nixosServerNetcup1 systemd[1]: Failed to start Redis instance bigbluebutton.
Mar 15 08:45:32 nixosServerNetcup1 systemd[1]: redis-bigbluebutton.service: Scheduled restart job, restart counter is at 4.
Mar 15 08:45:32 nixosServerNetcup1 systemd[1]: Stopped Redis instance bigbluebutton.
Mar 15 08:45:32 nixosServerNetcup1 systemd[1]: Starting Redis instance bigbluebutton...
Mar 15 08:45:32 nixosServerNetcup1 redis-server[16623]: 16623:C 15 Mar 2021 08:45:32.110 # WARNING supervised by systemd - you MUST set appropriate values for TimeoutStartSec and TimeoutStopSec in your service unit.
Mar 15 08:45:32 nixosServerNetcup1 redis-server[16623]: WARNING supervised by systemd - you MUST set appropriate values for TimeoutStartSec and TimeoutStopSec in your service unit.
Mar 15 08:45:32 nixosServerNetcup1 systemd[1]: redis-bigbluebutton.service: Failed with result 'protocol'.
Mar 15 08:45:32 nixosServerNetcup1 systemd[1]: Failed to start Redis instance bigbluebutton.
Mar 15 08:45:32 nixosServerNetcup1 systemd[1]: redis-bigbluebutton.service: Scheduled restart job, restart counter is at 5.
Mar 15 08:45:32 nixosServerNetcup1 systemd[1]: Stopped Redis instance bigbluebutton.
Mar 15 08:45:32 nixosServerNetcup1 systemd[1]: redis-bigbluebutton.service: Start request repeated too quickly.
Mar 15 08:45:32 nixosServerNetcup1 systemd[1]: redis-bigbluebutton.service: Failed with result 'protocol'.
Mar 15 08:45:32 nixosServerNetcup1 systemd[1]: Failed to start Redis instance bigbluebutton.
```
So it seems like I really have to set the timeouts.. after setting them to 5s each and changing the daemonize behaviour of redis to no according to [this](https://gist.github.com/hackedunit/a53f0b5376b3772d278078f686b04d38#gistcomment-2816179) comment, redis now runs fine. bbb-greenlight now gives me:
```
Mar 15 09:06:31 nixosServerNetcup1 bbb-greenlight-start[23680]: ArgumentError: Missing 'secret_key_base' for 'production' environment, set this string with 'rails credentials:edit'
```
is there a way to set that from the nix module?

EDIT: I also noticed, that all files in `/var/lib/secrects/` are empty but I guess that should not be the case.

**Comment by ajs124** [comment]
Interesting, redis works just fine for us, but good that you solved it in your setup.

For the secrets, there's a script somewhere that generates them. IIRC it's called `bbb-generate-secrets`, might be in its own package. I'm not sure if it overwrites everything probably or whatever, so you might want to drop the empty secrets, before you run it.

**Comment by timhae** [comment]
I saw that package, it does not overwrite the existing secrets but when I remove them manually the secrets that are created are empty.. but I will look into that.

**Comment by timhae** [comment]
please excuse the delay.. I managed to get the generate secrets script working, then greenlight failed because it could not connect to postgres so I simply changed the password manually and it worked. Now bbb-web fails to start with
```
Apr 27 21:59:12 nixosServerNetcup1 bbb-web[16811]: 21:59:12,972 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to ERROR
Apr 27 21:59:12 nixosServerNetcup1 bbb-web[16811]: 21:59:12,972 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
Apr 27 21:59:12 nixosServerNetcup1 bbb-web[16811]: 21:59:12,972 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
Apr 27 21:59:12 nixosServerNetcup1 bbb-web[16811]: 21:59:12,973 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@402c4085 - Registering current configuration as safe fallback point
Apr 27 21:59:13 nixosServerNetcup1 bbb-web[16811]: Exception in thread "main" java.lang.reflect.InvocationTargetException
Apr 27 21:59:13 nixosServerNetcup1 bbb-web[16811]:         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Apr 27 21:59:13 nixosServerNetcup1 bbb-web[16811]:         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Apr 27 21:59:13 nixosServerNetcup1 bbb-web[16811]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Apr 27 21:59:13 nixosServerNetcup1 bbb-web[16811]:         at java.lang.reflect.Method.invoke(Method.java:498)
Apr 27 21:59:13 nixosServerNetcup1 bbb-web[16811]:         at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
Apr 27 21:59:13 nixosServerNetcup1 bbb-web[16811]:         at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
Apr 27 21:59:13 nixosServerNetcup1 bbb-web[16811]:         at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
Apr 27 21:59:13 nixosServerNetcup1 bbb-web[16811]:         at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:58)
Apr 27 21:59:13 nixosServerNetcup1 bbb-web[16811]: Caused by: java.lang.AbstractMethodError: grails.boot.GrailsApp.setProperty(Ljava/lang/String;Ljava/lang/Object;)V
Apr 27 21:59:13 nixosServerNetcup1 bbb-web[16811]:         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setGroovyObjectProperty(ScriptBytecodeAdapter.java:532)
Apr 27 21:59:13 nixosServerNetcup1 bbb-web[16811]:         at grails.boot.GrailsApp.<init>(GrailsApp.groovy:76)
Apr 27 21:59:13 nixosServerNetcup1 bbb-web[16811]:         at grails.boot.GrailsApp.run(GrailsApp.groovy:454)
Apr 27 21:59:13 nixosServerNetcup1 bbb-web[16811]:         at grails.boot.GrailsApp.run(GrailsApp.groovy:443)
Apr 27 21:59:13 nixosServerNetcup1 bbb-web[16811]:         at grails.boot.GrailsApp$run.call(Unknown Source)
Apr 27 21:59:13 nixosServerNetcup1 bbb-web[16811]:         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
Apr 27 21:59:13 nixosServerNetcup1 bbb-web[16811]:         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
Apr 27 21:59:13 nixosServerNetcup1 bbb-web[16811]:         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
Apr 27 21:59:13 nixosServerNetcup1 bbb-web[16811]:         at org.bigbluebutton.web.Application.main(Application.groovy:8)
Apr 27 21:59:13 nixosServerNetcup1 bbb-web[16811]:         ... 8 more
Apr 27 21:59:13 nixosServerNetcup1 systemd[1]: bbb-web.service: Main process exited, code=exited, status=1/FAILURE
Apr 27 21:59:13 nixosServerNetcup1 systemd[1]: bbb-web.service: Failed with result 'exit-code'.
Apr 27 21:59:13 nixosServerNetcup1 systemd[1]: bbb-web.service: Consumed 3.213s CPU time, no IP traffic.
Apr 27 21:59:13 nixosServerNetcup1 systemd[1]: bbb-web.service: Scheduled restart job, restart counter is at 5.
Apr 27 21:59:13 nixosServerNetcup1 systemd[1]: Stopped the BigBlueButton web component.
Apr 27 21:59:13 nixosServerNetcup1 systemd[1]: bbb-web.service: Consumed 3.213s CPU time, no IP traffic.
Apr 27 21:59:13 nixosServerNetcup1 systemd[1]: bbb-web.service: Start request repeated too quickly.
Apr 27 21:59:13 nixosServerNetcup1 systemd[1]: bbb-web.service: Failed with result 'exit-code'.
Apr 27 21:59:13 nixosServerNetcup1 systemd[1]: Failed to start the BigBlueButton web component.
```
unfortunately I really don't know whats happening here, the web module suggests this is a grails application but I have no idea how to debug this, do you?

**Comment by ajs124** [comment]
That stack trace does not look familiar. Is there nothing in the logs above it?

**Comment by timhae** [comment]
[this](https://pastebin.com/LBGKpTzh) is the entire systemctl log when I try to start the service.

**Comment by ajs124** [comment]
Hm. Still can't say I've seen that before, sorry. Maybe something's wrong with some config file? You're running this from the 20.09 branch on NixOS 20.09, right?

**Comment by timhae** [comment]
yes, 20.09 NixOS and 20.09 branch of bbb4nix.

**Comment by dasJ** [comment]
20.09 is not supported anymore
